name: docker_test

#run-name:

on:
  workflow_dispatch:

jobs:
  basic-one:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: docker build
        run: |
          docker build . -t test

      - name: list of docker images
        run: docker images

      - name: run docker image
        run: docker run test

      - name: get status
        if: ${{ 
