name: docker_test

#run-name:

on:
  workflow_dispatch:

jobs:
  terrafom_plan:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: terraform init
        working-directory: ${{ github.workspace }}/terraform
        run: |
          terraform init
          terraform plan
          #terraform apply

  terraform_apply:
    runs-on: ubuntu-latest
    env: terrform_apply
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: terraform init
        working-directory: ${{ github.workspace }}/terraform
        run: |
          terraform init
          terraform plan
          terraform apply

          



      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: docker build
      #   run: |
      #     docker build . -t test

      # - name: list of docker images
      #   run: docker images

      # - name: run docker image
      #   run: docker run test



